name: Lesli workflow
on:
  pull_request:
    branches: [master, production]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  call-lesli-ci:
    uses: LesliTech/Lesli/.github/workflows/lesli-ci.yaml@master
